// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// prisma.config.ts
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",      // ruta a tu schema.prisma
  migrations: {
    path: "prisma/migrations",         // ruta de tus migraciones
  },
  datasource: {
    provider: "postgresql",            // ⚠ muy importante
    url: process.env.DATABASE_URL,     // usa tu variable de entorno
  },
});